.TH "elem" 3 "901771" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elem
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsinistra\fP"
.br
.ti -1c
.RI "int \fBdestra\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fB901771\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "int destra"

.PP
Definition at line \fB16\fP of file \fB901771\&.c\fP\&.
.SS "int sinistra"

.PP
Definition at line \fB15\fP of file \fB901771\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 901771 from the source code\&.
